name: First Workflow
on: [workflow_dispatch] # manualy trigger the workflow
jobs:
  first-job:
    runs-on: self-hosted
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: repo checkout
        uses: actions/checkout@v3
      - name: appscan-ci checkout
        run: git clone https://git.gtech.com/scm/appsec/appscan-ci.git
      - name: install python requirements
        run: python3.11 -m pip install -r appscan-ci/requirements.txt
      - name: ls -alh /home/roman
        run: ls -alh /home/roman
      - name: touch file
        run: touch /home/roman/AppScan/test_file
      - name: appscan-ci scripts run
        run: python3.11 appscan-ci/scan.py -n simpleiot-github -s simpleiot --noCompileScan all --useDocker True
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
#         with:
#           sarif_file: simpleiot/simpleIOT.sarif
#           category: testing
      - name: PWD
        run: pwd
      - name: List folder
        run: ls -lh
      - name: Print goodbye
        run: echo "Done - bye!" 