name: First Workflow
on: [workflow_dispatch] # manualy trigger the workflow
jobs:
  first-job:
    runs-on: self-hosted
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: repo checkout
        uses: actions/checkout@v3
      - name: appscan-ci checkout
        run: git clone https://git.gtech.com/scm/appsec/appscan-ci.git
      - name: install python requirements
        run: python3.11 -m pip install -r appscan-ci/requirements.txt
      - name: appscan-ci scripts run
        run: |
          export LOCAL_REPO=/home/roman/AppScan
          export M2_REPO=/home/roman/.m2/repository
          python3.11 appscan-ci/scan.py -n simpleiot-GitHub -s simpleiot --noCompileScan all --useDocker True
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: /home/roman/AppScan/simpleiot-github/sarifs/simpleiot-github.sarif
          category: testing
      - name: PWD
        run: pwd
      - name: List folder
        run: ls -lh
      - name: Print goodbye
        run: echo "Done - bye!" 
