name: First Workflow
on: [workflow_dispatch] # manualy trigger the workflow
jobs:
  first-job:
    runs-on: self-hosted
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: repo checkout
        uses: actions/checkout@v3
      - name: appscan-ci checkout
        run: git clone https://git.gtech.com/scm/appsec/appscan-ci.git
#       - name: SimpleIOT test
#         run: docker run -i --rm --env-file /home/roman/env.list --add-host usriappscansv:10.253.160.244 --volume ./simpleiot:/simpleiot 10.253.160.58:5002/appscan/appscan-src-cli:latest script /simpleiot/SimpleIOT.scan
#       - name: Sleep now
#         run: sleep 60
#       - name: Upload SARIF file
#         uses: github/codeql-action/upload-sarif@v2
#         with:
#           sarif_file: simpleiot/simpleIOT.sarif
#           category: testing
      - name: PWD
        run: pwd
      - name: List folder
        run: ls -lh
      - name: Print goodbye
        run: echo "Done - bye!" 